# This file configures the OOI beta instance configuration

load_sequence:

  # Copied from ooi_load_config.yml
  - name: load_OOIR2_ui
    docstring: Loads the UI definition
    config:
      op: loadui
      ui_path: 'http://userexperience.oceanobservatories.org/database-exports/Candidates'
      attachments: res/preload/r2_ioc/attachments

  - name: load_OOIR2_scenario
    docstring: Loads the basic OOI resources, such as Orgs, Users etc
    config:
      op: load
      scenario: OOIR2

  - name: load_parameter_scenarios
    docstring: Loads basic shared parameter and stream resources
    config:
      op: load
      scenario: BETA
      categories: ParameterFunctions,ParameterDefs,ParameterDictionary,StreamDefinition
      clearcols: owner_id,org_ids
      assets: res/preload/r2_ioc/ooi_assets
      parseooi: True

  - name: load_ooi_assets
    docstring: Main OOI preload fed by SAF and OOI preload spreadsheet shources
    config:
      op: load
      loadooi: True
      assets: res/preload/r2_ioc/ooi_assets
      ooiuntil: "12/31/2013"
      ooiparams: True


  # THIS IS THE ACTUAL BETA SPECIALIZATION
  - name: load_OOIR2_demo
    docstring: Some simulators with data products
    config:
      op: load
      scenario: OOIR2_DEMO
      idmap: True

  - name: load_OOIR2_beta
    docstring: Specialize for beta (port agent addresses in InstrumentAgentInstance)
    config:
      op: load
      scenario: OOIR2_BETA

  - name: load_glider
    docstring: Load glider platform and instruments
    config:
      op: load
      scenario: GENG,CTDGV,FLORD,DOSTA
      idmap: True
      categories: ExternalDatasetAgent,ParameterFunctions,ParameterDefs,ParameterDictionary,StreamConfiguration,IDMap

  - name: load_mflm
    docstring: Load MFLM instruments
    config:
      op: load
      scenario: SP_MFLM
      idmap: True
      categories: ExternalDatasetAgent,ParameterFunctions,ParameterDefs,ParameterDictionary,StreamConfiguration,IDMap

  - name: load_beta_instruments
    docstring: Load physical instrument sites, devices and agent instance definitions for the beta system
    config:
      op: load
      scenario: PREST,TMPSF,VEL3D_B,OPTAA,CTDPF
      idmap: True
      excludecategories: InstrumentModel

  - name: load_RSN_OMS
    docstring: Load platform and VEL3D_B instrument for life OMS connection (depends on VEL3D_B above)
    config:
      op: load
      scenario: RSN_OMS
      idmap: True
      excludecategories: InstrumentModel

  - name: load_ooi_assets2
    docstring: Reapply OOI preload to finish off data product generation
    config:
      op: load
      loadooi: True
      assets: res/preload/r2_ioc/ooi_assets
      ooiuntil: "12/31/2013"
      ooiparams: True
